sudo: false

language: node_js

node_js:
  - "8"

notifications:
  email: false

install:
  - npm run bootstrap
  - npm prune

script:
  - npm run test

#after_script:
#  - coveralls < ./coverage/remapped/lcov.info || true
